// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhqnsnlcajfvraqlqnvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpocW5zbmxjYWpmdnJhcWxxbnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTUyOTAsImV4cCI6MjA3MjAzMTI5MH0.MF0KOP-VMgxSaxR_GMk3Zdl8AlzdVuDuc9a49N0RlpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});